# -*- coding: utf-8 -*-
from easy_thumbnails.conf import Settings


class OptimizeSettings(Settings):
    THUMBNAIL_OPTIMIZE_COMMAND = { 'png': None, 'jpeg': None, 'gif': None }
    """
    Postprocess thumbnails of type PNG, GIF or JEPG after transformation but before storage.

    Applies an external post processing image manipulation program, which can be used to reduce
    the payload of the thumbnailed image files generated by PIL/Pillow. This is a typically
    suggested by tools such as Google's PageSpeed.
    Example: THUMBNAIL_OPTIMIZE_COMMAND = {
        'png': '/usr/bin/optipng {filename}',
        'gif': '/usr/bin/optipng {filename}',
        'jpeg': '/usr/bin/jpegoptim {filename}'
    }
    Note that optipng can also optimize images of type GIF.
    """

settings = OptimizeSettings()
